remote_theme: chesterhow/tale

title: Keisuke Suzuki

plugins:
  - jekyll-paginate-v2
  - jekyll-remote-theme
  - jekyll-last-modified-at

pagination:
  enabled: true
  per_page: 10

include:
  - "memo/postgresql/img"

# custom parameters
author:
  name: Keisuke Suzuki
