remote_theme: chesterhow/tale

title: Keisuke Suzuki

encoding: UTF-8

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

paginate: 10

excerpt_separator: "<!--end_excerpt-->"

# custom parameters
author:
  name: Keisuke Suzuki

repository: yajirobee/logs
