remote_theme: chesterhow/tale

title: Keisuke Suzuki

permalink: /:year-:month-:day/:title
paginate: 10

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# custom parameters
author:
  name: Keisuke Suzuki
